Fix netdata installation
Use POSIX shell, avoid bashism like process substitution

Add integrity check on the installer before using it.

Fixes issue #279

diff --git a/src/roles/netdata/tasks/main.yml b/src/roles/netdata/tasks/main.yml
--- a/src/roles/netdata/tasks/main.yml
+++ b/src/roles/netdata/tasks/main.yml
@@ -1,10 +1,12 @@
 ---
-## We're called from the site.yml playbook and the haproxy role takes care of front-end and back-end port handling
-##
-## Add test to see if it's already installed and skip if it is
+# We're called from the site.yml playbook 
+# The haproxy role takes care of front-end and back-end port handling
+
+# Netdata used to install in /opt but now uses packages across the system.
+# "/usr/sbin/netdata" is the main binary.
 - name: Check if Netdata is present
   stat:
-    path: "{{ m_install }}/netdata"
+    path: "/usr/sbin/netdata"
   register: netdata_present
 
 - ansible.builtin.debug: msg="netdata not installed"
@@ -13,10 +15,25 @@
 - ansible.builtin.debug: msg="netdata installed"
   when: netdata_present.stat.exists == True
 
-## It will be running once installed
-- name: Install Intel/AMD 64bit static build of Netdata
-  shell: sh <(curl -Ss https://get.netdata.cloud/kickstart.sh) --dont-wait
-  args:
-    executable: /bin/sh
+- name: Verify Netdata installer script integrity
+  ansible.builtin.shell: |
+    if [ "39321e7a8e05f0054f93df1824189abd" = "$(curl -Ss https://get.netdata.cloud/kickstart.sh | tee /tmp/netdata-kickstart.sh | md5sum | cut -d ' ' -f 1)" ]; then
+      echo "OK, VALID: Netdata installer script integrity verified"
+      exit 0
+    else
+      echo "FAILED, INVALID: Netdata installer script integrity check failed"
+      exit 1
+    fi
+  register: netdata_integrity_check
   become: false
   when: netdata_present.stat.exists == False
+
+## It will be running once installed
+# The default port is 19999, but we do not open any port in HAProxy so it's not
+# accessible externally unless the admin wants to do so manually.
+# It is recommended to just use port forwarding over SSH to access the Netdata dashboard securely.
+# You can do this in your ssh config, or with VSCode port forwarding.
+- name: Install Intel/AMD 64bit static build of Netdata
+  ansible.builtin.shell: sh /tmp/netdata-kickstart.sh --stable-channel --install-prefix {{ m_install }} --build-only --non-interactive --disable-telemetry
+  become: false
+  when: netdata_present.stat.exists == False and netdata_integrity_check.rc == 0
