Convert to using a declarative approach for wikis
You can now declare wiki IDs, names, aliases, and other
attributes for wikis in YAML. This deprecates the implied or indirect
directory method of creating and identifying wikis.

The deprecated directory method is still supported.

There is a new meza command 'migrate-wikis' that will write the YAML
for you - storing it in your conf-meza/public/public.yml file.
Usage: sudo meza migrate-wikis <environment>
e.g. sudo meza migrate-wikis monolith

See config/defaults.yml for example declaration

You can now use Meza commands to 'create' wiki and 'delete' wiki.
However, you can now also simply edit your YAML configuration and
run a meza deploy which will create wikis accordingly.

New:
- manual/meza-cmd/migrate-wikis.txt
- src/playbooks/migrate-wikis.yml
- src/roles/base-config-scripts/templates/wiki-config.php.j2
- src/roles/migrate-to-declarative-wikis/tasks/main.yml
Modified:
- config/defaults.yml
- src/roles/base-config-scripts/tasks/main.yml
- src/roles/base-config-scripts/templates/config.sh.j2
- src/roles/configure-wiki/tasks/main.yml
- src/roles/delete-wiki-wrapper/tasks/main.yml
- src/roles/mediawiki/tasks/main.yml
- src/roles/mediawiki/templates/LocalSettings.php.j2
- src/roles/mediawiki/templates/refresh-links.sh.j2
- src/roles/mediawiki/templates/smw-rebuild-all.sh.j2
- src/roles/set-vars/tasks/main.yml
- src/scripts/meza.py
- src/scripts/unifyUserTables.php

Fixes Issue #101

diff --git a/src/roles/mediawiki/templates/smw-rebuild-all.sh.j2 b/src/roles/mediawiki/templates/smw-rebuild-all.sh.j2
--- a/src/roles/mediawiki/templates/smw-rebuild-all.sh.j2
+++ b/src/roles/mediawiki/templates/smw-rebuild-all.sh.j2
@@ -2,27 +2,32 @@
 
 source "{{ m_install }}/.deploy-meza/config.sh"
 
+# Use declarative wiki configuration (from config.sh MEZA_WIKIS variable)
 if [ -z "$1" ]; then
-	do_wikis="*/"
+	# Process all configured wikis
+	for wiki_id in $MEZA_WIKIS; do
+		if [ ! -d "{{ m_htdocs }}/wikis/$wiki_id" ]; then
+			echo "\"$wiki_id\" not a valid wiki ID (directory missing)"
+			continue
+		fi
+		# Process this wiki (rest of script logic follows)
+		_process_wiki_smw_rebuild "$wiki_id"
+	done
+	exit 0
 else
-	do_wikis="$1"
+	# Process single specified wiki
+	wiki_id="$1"
+	if [ ! -d "{{ m_htdocs }}/wikis/$wiki_id" ]; then
+		echo "\"$wiki_id\" not a valid wiki ID (directory missing)"
+		exit 1
+	fi
+	_process_wiki_smw_rebuild "$wiki_id"
+	exit 0
 fi
 
-wiki_dir="{{ m_htdocs }}/wikis"
-
-cd "$wiki_dir"
-for d in $do_wikis; do
-
-	if [ -z "$1" ]; then
-		wiki_id=${d%/}
-	else
-		wiki_id="$d"
-	fi
-
-	if [ ! -d "$wiki_dir/$wiki_id" ]; then
-		echo "\"$wiki_id\" not a valid wiki ID"
-		continue
-	fi
+# Function to process SMW rebuild for a single wiki
+_process_wiki_smw_rebuild() {
+	local wiki_id="$1"
 
 	timestamp=$(date +"%F_%T")
 	exception_log="{{ m_logs }}/smw-rebuilddata-exceptions-$wiki_id-$timestamp.log"
@@ -95,4 +100,4 @@ for d in $do_wikis; do
 		echo "rebuildData completed for \"$wiki_id\" at $endtimestamp"
 	fi
 
-done
+}
